### ISSUE TITLE
405_DQN貌似没有保存done

### ISSUE THREAD

**Issue by hccz95** [MorvanZhou/PyTorch-Tutorial#102]
405_DQN的代码在存储经验时，好像没有保存done，在计算Q时，也没有区分是否是终态

**Comment by zhangjianguo-max** [comment]
老师你好，在记忆存储模块，我运行代码使其输出index的值，发现他的数值一值是在1-200之间循环显示，这是否代表存储的记忆只是每个回合的，并没有将记忆进行累计存储。或者说记忆库没有发挥作用，即时在记忆库没存储满之前，每次存储新的回合都会将老的记忆覆盖。想请教一下

**Comment by hccz95** [comment]
> 

index只是这个transition处于其所在episode中的序号
