### ISSUE TITLE
 PyTorch was compiled without numpy support

### ISSUE THREAD

**Issue by IJustLoveMyself** [MorvanZhou/PyTorch-Tutorial#13]
我运行这个源码。python2.7 
出现错误：Traceback (most recent call last):
  File "./LR_test.py", line 51, in <module>
    plt.scatter(x.data.numpy(), y.data.numpy())
RuntimeError: PyTorch was compiled without numpy support
但是我安装的时候运行了conda install numpy pyyaml mkl setuptools cmake cffi这句话，这是什么原因啊

**Comment by MorvanZhou** [comment]
请问你装numpy的时候确定装到了py2吗，有可能装到了py3

**Comment by MorvanZhou** [comment]
也有可能是conda的原因，我没用过conda, 不太确定如果是conda应该怎么用

**Comment by IJustLoveMyself** [comment]
问题解决了，主要问题是1、我之前通过源码安装的时候遇到错误：error: could not create '/home/xiaofeng/anaconda2/lib/python2.7/site-packages/torch': Permission denied
然后我就运行sudo  python setup.py install来进行安装。结果torch被默认安装在了我ubuntu系统自带的python2.7的文件夹（/usr/local/lib/python2.7/dist-packages/）下面，所以我之前执行程序的时候一直需要通过sudo来执行，不然提示找不到torch的模块。而numpy pyyaml mkl setuptools cmake cffi这些依赖安装在了anaconda2的文件夹下面。anaconda也包含了一个python2.7.如果我不通过sudo来执行程序的话，就会默认使用的是anaconda中安装的python2.7 所以这就造成了一个问题：sudo来执行程序，默认系统自带的python2.7，提示torch的依赖没有安装，如果不通过sudo来执行程序的话，默认的是anaconda带的python2.7 ，提示找不到torch模块。我最后重新通过源码安装了pytorch，没有用sudo直接python setup.py install。提示文件夹没有权限的，我用chmod来解决了。

**Comment by IJustLoveMyself** [comment]
我运行了这个源码，但是现象和视频的不太一样，我将 loss.data[0] 打印出来
“
0.662851333618
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
”
但是好像后面的loss都一样，出现的图也是直线，没有进行拟合回归，我将程序和你视频里的程序对比了，应该是一样的。

**Comment by IJustLoveMyself** [comment]
我运行了这个源码，但是现象和视频的不太一样，我将 loss.data[0] 打印出来
“
0.662851333618
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
0.0932437628508
”
但是好像后面的loss都一样，出现的图也是直线，没有进行拟合回归，我将程序和你视频里的程序对比了，应该是一样的。

然后我将学习效率 改成了0.1 训练次数改成了1000，出现了拟合回归的过程。刚开始学这个，只是知道这个程序的大概原理，还有一点就是参数初始化这点，比如直线y=wa+b ,这个w的初始化时pytorch会给一个默认值么，我们不需要进行指定么

**Comment by MorvanZhou** [comment]
torch 初始化 w,b 的时候会默认使用 uniform distribution (如果我没记错的话). 关于初始化参数设置, 你可以参考一下我这个[code](https://github.com/MorvanZhou/PyTorch-Tutorial/blob/master/tutorial-contents/504_batch_normalization.py#L74-L76)
