### ISSUE TITLE
Err in 403_RNN_regressor.py

### ISSUE THREAD

**Issue by planewave** [MorvanZhou/PyTorch-Tutorial#23]
https://github.com/MorvanZhou/PyTorch-Tutorial/blob/68396f597200ee9c9f5fb9eb0145969f7646b5f4/tutorial-contents/403_RNN_regressor.py#L86

> RuntimeError: input and target shapes do not match: input [10 x 1], target [1 x 10 x 1]

I think 
`y = Variable(torch.from_numpy(y_np[np.newaxis, :, np.newaxis]))`
 should be 
`y = Variable(torch.from_numpy(y_np[:, np.newaxis]))
`

could you also update your code to be compatible to version 0.4.0. I mean removing **Variable**

Thank you

**Comment by MorvanZhou** [comment]
Thanks, I have updated the code to the new version.
