### ISSUE TITLE
新版本pytorch在401_CNN中的一个小bug

### ISSUE THREAD

**Issue by gintamatyy** [MorvanZhou/PyTorch-Tutorial#26]
122行的代码：accuracy = sum(pred_y == test_y) / float(test_y.size(0))    在0.4.0的新版本下运行报错：“RuntimeError: value cannot be converted to type uint8_t without overflow: 2000.000000”
并且sum(pred_y == test_y) 求出来的值也不是pred_y和test_y相等的值（会小很多）
我试了下把sum(pred_y == test_y) 改成 torch.sum(pred_y == test_y).numpy()，可以求出正确结果，但是我不知道是为什么前面的代码不能用了，莫凡大神能解答一下吗？谢谢！

**Comment by MorvanZhou** [comment]
你好, 我修改了一下代码, 已兼容了新版本.
 float(sum(pred_y == test_y)) / float(test_y.size(0))
