### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by guohaoghp** [MorvanZhou/PyTorch-Tutorial#3]
Thanks to the effort of Morvanzhou, I got a wonderful start of deep learning,but for this one, code403, I got a little confused that how to change these codes of RNN into the kind of LSTM.I wish you can show it to me,thanks a lot.

**Comment by MorvanZhou** [comment]
Hi @guohaoghp , I think the RNN should be attached to the encoder for handling the timely input. The decoder will output result for every time step. If you want to visualize the output from the encoder, I think you have to use the return at the last time step. 
The RNN code would be similar to this code: https://github.com/MorvanZhou/PyTorch-Tutorial/blob/master/tutorial-contents/402_RNN_classifier.py

**Comment by guohaoghp** [comment]
Thanks a lot for your reply, it helps a lot.
