### ISSUE TITLE
numpy 1.12版本不支持 float 类型的indices

### ISSUE THREAD

**Issue by Evanzhou123** [MorvanZhou/PyTorch-Tutorial#33]
当代码运行到89行时，程序报错slice indices must be integers or None or have an __index__ method。但是如果将b_x转换为int类型会导致RuntimeError: Expected object of type torch.FloatTensor but found type torch.IntTensor for argument #4 'mat1'

**Comment by MorvanZhou** [comment]
没有跟进，所以关闭issue
