### ISSUE TITLE
201_torch_numpy.ipynb won't open in GitHub

### ISSUE THREAD

**Issue by Bruno-Hanzen** [MorvanZhou/PyTorch-Tutorial#35]
201_torch_numpy.ipynb does not load in the GitHub interface, while 202_variable.ipynb opens without any problem

**Comment by MorvanZhou** [comment]
I have updated 201_torch_numpy.ipynb, could you reopen this file and check if works?

**Comment by Bruno-Hanzen** [comment]
I have just checked; it works now. Thanks.
