### ISSUE TITLE
基于torch的一个库,animal_human_kp，其中标注文件是npy格式的，请问这种格式的文件应该怎样制作

### ISSUE THREAD

**Issue by pprp** [MorvanZhou/PyTorch-Tutorial#38]
[https://github.com/menorashid/animal_human_kp](https://github.com/menorashid/animal_human_kp)

## 目前我进行的研究需要用到以上的github库，那个库的数据标注文件是npy格式的，想请教一下莫烦，这种npy格式文件是如何生成的，如果想要制作自己的数据集，应该怎么做？

谢谢

**Comment by MorvanZhou** [comment]
你好，“npy”是numpy存储的数据。具体可以参考这个： https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.save.html

**Comment by pprp** [comment]
Thank you谢谢莫烦，我以后也会继续支持你的！！
