### ISSUE TITLE
Error on "401_CNN.ipynb"

### ISSUE THREAD

**Issue by redhat12345** [MorvanZhou/PyTorch-Tutorial#42]
Hi,

I am getting the following error when I run the 401_CNN.ipynb. Please help me to resolve that.

Thank you in advance.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-64136a05fa7f> in <module>()
     34                 low_dim_embs = tsne.fit_transform(last_layer.data.numpy()[:plot_only, :])
     35                 labels = test_y.numpy()[:plot_only]
---> 36                 plot_with_labels(low_dim_embs, labels)
     37 plt.ioff()

<ipython-input-12-64136a05fa7f> in plot_with_labels(lowDWeights, labels)
      8     for x, y, s in zip(X, Y, labels):
      9         c = cm.rainbow(int(255 * s / 9)); plt.text(x, y, s, backgroundcolor=c, fontsize=9)
---> 10     plt.xlim(X.min(), X.max()); plt.ylim(Y.min(), Y.max()); plt.title('Visualize last layer'); plt.show(); plt.pause(0.01)
     11 
     12 plt.ion()

~/pytorch_python3/lib/python3.5/site-packages/matplotlib/pyplot.py in pause(interval)
    292         canvas.start_event_loop(interval)
    293     else:
--> 294         time.sleep(interval)
    295 
    296 

NameError: name 'time' is not defined

**Comment by MorvanZhou** [comment]
Please update matplotlib since it looks like a function is missing in the matplotlib
