### ISSUE TITLE
Got an error when backward

### ISSUE THREAD

**Issue by liumarcus70s** [MorvanZhou/PyTorch-Tutorial#45]
D_loss.backward(retain_variables=True)      # retain_variables for reusing computational graph

got an error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-5152ddc0cc4d> in <module>()
     11 
     12     opt_D.zero_grad()
---> 13     D_loss.backward(retain_variables=True)      # retain_variables for reusing computational graph
     14     opt_D.step()
     15 

TypeError: backward() got an unexpected keyword argument 'retain_variables'

**Comment by MorvanZhou** [comment]
Hi, have you updated pytorch to the version 0.4?
