### ISSUE TITLE
cnn=CNN()后，cnn不能用, 如何解决？

### ISSUE THREAD

**Issue by mxie622** [MorvanZhou/PyTorch-Tutorial#48]
问题如下：
（除此之外代码还有好多其他的问题。。我2.7和3.6都试了，不管用。。。谢谢老师。。。）
TypeError                                 Traceback (most recent call last)
<ipython-input-1-080b4a677624> in <module>
     97     for step, (b_x, b_y) in enumerate(train_loader):   # gives batch data, normalize x when iterate train_loader
     98 
---> 99         output = cnn(b_x)[0]               # cnn output
    100         loss = loss_func(output, b_y)   # cross entropy loss
    101         optimizer.zero_grad()           # clear gradients for this training step

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    355             result = self._slow_forward(*input, **kwargs)
    356         else:
--> 357             result = self.forward(*input, **kwargs)
    358         for hook in self._forward_hooks.values():
    359             hook_result = hook(self, input, result)

<ipython-input-1-080b4a677624> in forward(self, x)
     68 
     69     def forward(self, x):
---> 70         x = self.conv1(x)
     71         x = self.conv2(x)
     72         x = x.view(x.size(0), -1)           # flatten the output of conv2 to (batch_size, 32 * 7 * 7)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    355             result = self._slow_forward(*input, **kwargs)
    356         else:
--> 357             result = self.forward(*input, **kwargs)
    358         for hook in self._forward_hooks.values():
    359             hook_result = hook(self, input, result)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/container.py in forward(self, input)
     65     def forward(self, input):
     66         for module in self._modules.values():
---> 67             input = module(input)
     68         return input
     69 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    355             result = self._slow_forward(*input, **kwargs)
    356         else:
--> 357             result = self.forward(*input, **kwargs)
    358         for hook in self._forward_hooks.values():
    359             hook_result = hook(self, input, result)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/conv.py in forward(self, input)
    280     def forward(self, input):
    281         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 282                         self.padding, self.dilation, self.groups)
    283 
    284 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/functional.py in conv2d(input, weight, bias, stride, padding, dilation, groups)
     88                 _pair(0), groups, torch.backends.cudnn.benchmark,
     89                 torch.backends.cudnn.deterministic, torch.backends.cudnn.enabled)
---> 90     return f(input, weight, bias)
     91 
     92 

TypeError: argument 0 is not a Variable

**Comment by MorvanZhou** [comment]
你好请问你的torch版本是多少？我在0.4.1下测试时ok的。

**Comment by mxie622** [comment]
版本有点低
0.3.1
而且不单是这个原因，更多的是我在ANACONDA里面跑不了，一跑kernel就挂。。。

**Comment by mxie622** [comment]
Mikes-MacBook-Pro:~ mikexie$ pip3 install pytorch==0.4.10

Collecting pytorch==0.4.10

  Could not find a version that satisfies the requirement pytorch==0.4.10
(from versions: 0.1.2)

No matching distribution found for pytorch==0.4.10

Mikes-MacBook-Pro:~ mikexie$


没法装你的这个版本。

**Comment by mxie622** [comment]
我原来用conda装也只能到0.3.1
这个问题咋解决啊。。。如果是这个版本,那课程里的。。optimizer,
提取神经网络，classification还有这个CNN都有部分代码是出错的。后面的我暂时没有试。

**Comment by MorvanZhou** [comment]
请从这里安装 https://pytorch.org/get-started/locally/

**Comment by mxie622** [comment]
感谢莫凡老师的视频教学，我已经用别的办法解决这些问题了, 全部都是版本问题.
