### ISSUE TITLE
PyTorch-Tutorial/tutorial-contents/504_batch_normalization.py fix RuntimeError

### ISSUE THREAD

**Issue by lugeluge** [MorvanZhou/PyTorch-Tutorial#50]
Add a line statement below the end of  Net class：
if __name__ == '__main__':
![image](https://user-images.githubusercontent.com/16603407/48112338-02ce2600-e291-11e8-8083-1588f3b83a96.png)
Then indent the code below。
Search the code l.append(loss_func(pred, test_y).data[0])  replace .data[0] with .item() to fix the waring
E:/code/python/learnPytorch/test1.py:121: UserWarning: invalid index of a 0-dim tensor. This will be an _error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  l.append(loss_func(pred, test_y).data[0])_
![image](https://user-images.githubusercontent.com/16603407/48112447-72441580-e291-11e8-9c60-24f5c0933845.png)

**Comment by MorvanZhou** [comment]
Thanks and fixed
