### ISSUE TITLE
306_optimizer.ipynb warning

### ISSUE THREAD

**Issue by keineahnung2345** [MorvanZhou/PyTorch-Tutorial#54]
In the 10th cell, `l_his.append(loss.data[0])` should be `l_his.append(loss.item())` to suppress warning.

> /opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:14: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by MorvanZhou** [comment]
Thanks and fixed
