### ISSUE TITLE
Bug in 401_CNN.ipynb

### ISSUE THREAD

**Issue by keineahnung2345** [MorvanZhou/PyTorch-Tutorial#56]
Besides bugs mentioned in https://github.com/MorvanZhou/PyTorch-Tutorial/pull/55, 
`print('Epoch: ', epoch, '| train loss: %.4f' % loss.data[0], '| test accuracy: %.2f' % accuracy)` 
should be replaced with
`print('Epoch: ', epoch, '| train loss: %.4f' % loss.item(), '| test accuracy: %.2f' % accuracy)` 
to suppress the following warning:

> /opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:41: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by MorvanZhou** [comment]
Thanks for the update
