### ISSUE TITLE
403: question about h_state = h_state.data

### ISSUE THREAD

**Issue by keineahnung2345** [MorvanZhou/PyTorch-Tutorial#57]
Dear author:

In 403, when I commented `h_state = h_state.data`, it gave me the following error:

> RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

And later I found the error can actually be solved by `loss.backward(retain_graph=True)`. 

I wonder what exactly does the error mean. And how does `h_state = h_state.data` solve the problem?

Thanks in advance.

**Comment by MorvanZhou** [comment]
Hi, which version of the pytorch are you using? This code is based on pytorch=0.4
