### ISSUE TITLE
406_GAN.py：报梯度计算时变量被inplace操作修改错误

### ISSUE THREAD

**Issue by xub-xubin** [MorvanZhou/PyTorch-Tutorial#89]
Morvan老师，

你好！我在运行406_GAN.py时，报了如下错误：
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [128, 1]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
能帮忙看一下是什么原因吗？谢谢

使用版本：
pytorch：1.5.0
python：3.7.4

**Comment by FUQiaobo** [comment]
me too

**Comment by zhaoyujingpy** [comment]
me toto

**Comment by sijiali57** [comment]
这个问题的答案看这里： https://github.com/pytorch/pytorch/issues/39141

问题来源主要是opt_D.step()变动了参数，原本pytorch1.4没有这一步的in place 检查。在1.5 版本他们加入了这个检查，所以如果你是1.4版本不会报错，但是1.5版本会报错。

**Comment by MorvanZhou** [comment]
已按照Pull request修复,感谢
