### ISSUE TITLE
pytorch 0.2 max method changed

### ISSUE THREAD

**Issue by SSARCandy** [MorvanZhou/PyTorch-Tutorial#9]
After I upgrade to pytorch 0.2

The example code in `405_DQN_Reinforcement_learning.py` is broken.
This is because `torch.max()` change it's return.

So the code need to change to run in pytorch 0.2:

LN:62
```py
action = torch.max(actions_value, 1)[1].data.numpy()[0, 0]

# change to
action = torch.max(actions_value, 1)[1].data.numpy()[0]
```

LN:90
```py
 q_target = b_r + GAMMA * q_next.max(1)[0]

# change to 
 q_target = b_r + GAMMA * q_next.max(1)[0].view(32, 1)
```

---

Thanks for you tutorial, it help me a lot!!

**Comment by MorvanZhou** [comment]
Thanks and updated
